spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  aplication:
    name: "project.artifactId@"
  profiles:
    active: local
  data:
    web:
      pageable:
        max-page-size: 2147483647
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB