##################
#### API INFO ####
##################

swagger.info.title=API Nord Tool - Apartamentos
swagger.info.description=Projeto para controle de vistoria e revistoria de apartamentos
swagger.info.version=1.0v
swagger.info.termsOfServiceUrl=CopyRight
swagger.info.contactName=Nicolas Correia
swagger.info.contactUrl=site
swagger.info.contactEmail=correia2comercial@gmail.com


##############################################
################## HEALTH ####################
##############################################
swagger.api.operation.health.value = Health
swagger.api.operation.health.notes = Método responsável por confirmar que a API esta funcionando.