SPS.BUSCAR_TODOS_DIA_SEMANA=\
SELECT \
    ds.id_dia_semana AS idDiaSemana, \
    ds.nm_dia_semana AS nmDiaSemana \
FROM dia_semana ds

SPS.BUSCAR_TODOS_STATUS_VISTORIA=\
SELECT \
    sv.id_status_vistoria AS idStatusVistoria, \
    sv.nm_status_vistoria AS nmStatusVistoria \
FROM status_vistoria sv 